### ISSUE TITLE
Ruby Sass is deprecated

### ISSUE THREAD

**Issue by csuhta** [sass/sassc-rails#105] opened 2018-08-08 02:24 UTC
```
$ bundle install
[...]
Installing sassc-rails 1.3.0
[...]
Post-install message from sass:

Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
```

**Comment by nschonni** [comment] 2018-08-08 03:09
Duplicate of #75

**Comment by SViccari** [comment] 2018-09-11 20:15
I'd love to know more about this issue as I'm uncertain if this is actually a duplicate of #75. Perhaps I'm just overlooking it but this library has a depdency on ruby sass and I haven't found a discusion about it's potential removal. 

There is a comment [here](https://github.com/sass/sassc-rails/blob/550bc2a272a31c252f2bcd43a8ce6476ff7ca8ed/sassc-rails.gemspec#L26-L28) that states the gem was added "for now". 

Do you know if there's a plan to remove `sass` from this project?

**Comment by bolandrm** [comment] 2018-09-12 13:36
Hi @SViccari, I believe you are correct that this is *not* a duplicate of #75.

The plan is to remove `sass` from this project as soon as possible.  We are currently working to release a 2.0.0 version of the sassc-ruby gem that underlies this project (https://github.com/sass/sassc-ruby/pull/85), and then we can work to remove sass as a dependency from this library as well.

**Closed** 2019-05-03 12:41 UTC
