### ISSUE TITLE
`RAILS_ENV=production rake assets:precompile` does not work

### ISSUE THREAD

**Issue by rosenfeld** [sass/sassc-rails#53] opened 2016-01-04 21:38 UTC
When trying to deploy my app with Capistrano I noticed a problem related to `sassc-rails` and had to rollback to `sass-rails` for the time being. While `rake assets:precompile` works fine, when `RAILS_ENV` is set to something else than development the task will fail with:

```
RAILS_ENV=production rake assets:precompile
rake aborted!
SassC::SyntaxError: Error: Data context created with empty source string
/home/rodrigo/temp/src/rails-projects/sasscsample/app/assets/stylesheets/main.scss:1
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

You can give it a try in this sample application I created to reproduce the problem:

https://github.com/rosenfeld/sassc-precompile-bug

**Comment by bolandrm** [comment] 2016-01-08 15:58
Appears to be duplicate of https://github.com/sass/sassc-rails/issues/49

**Closed by bolandrm** 2016-01-08 15:58 UTC
